build-res/subfloor.xml
build.properties
ivy.xml

Merge of master into future-develop

Auto-Merge refreshing development branch

---

src/org/pentaho/metadata/model/olap/OlapAnnotation.java
src/org/pentaho/metadata/util/MondrianModelExporter.java
test/org/pentaho/metadata/MondrianModelExporterTest.java

@bytekast @kurtwalker @pamval please review

[BACKLOG-3146] descriptions in analyzer

---

src/org/pentaho/metadata/model/olap/OlapAnnotation.java
src/org/pentaho/metadata/util/MondrianModelExporter.java

[BACKLOG-3146] handle escaping in exporter to avoid gwt issues

---

src/org/pentaho/metadata/model/LogicalModel.java
src/org/pentaho/metadata/model/olap/OlapCalculatedMember.java
src/org/pentaho/metadata/model/olap/OlapCube.java
src/org/pentaho/metadata/model/olap/OlapRole.java
src/org/pentaho/metadata/util/MondrianModelExporter.java
src/org/pentaho/metadata/util/XmiParser.java
test/org/pentaho/metadata/MondrianModelExporterTest.java
test/org/pentaho/metadata/XmiParserTest.java

@pminutillo @kurtwalker @bytekast @DFieldFL This pull request includes Will's code review feedback.

Support for roles/calculated measures in metadata

---

test-res/olap-cubes-sample.xml
test-res/olap-roles-sample.xml
test/org/pentaho/metadata/model/olap/util/OlapUtilTest.java

@bennychow @DFieldFL @kurtwalker @bytekast Please review whenever you get a chance

[BACKLOG-2875] Unit tests for OlapUtil class

---

src/org/pentaho/metadata/query/model/util/QueryXmlHelper.java
test/org/pentaho/metadata/query/model/util/QueryXmlHelperTest.java

Backport of https://github.com/pentaho/pentaho-metadata/pull/62
@tmorgner 
Please review.

SP-1918 - Backport of PDB-1844 - PIR report in dashboard widget displays fields which were deleted from datasource. (5.4 Suite)

---

src/org/pentaho/pms/mql/dialect/HypersonicDialect.java
test/org/pentaho/pms/mql/dialect/HypersonicDialectTest.java

- Added override method getDateSQL to return properly formatted timestamp;
- Added unit test for the new method;

[BACKLOG-4800] - Update to HypersonicDialect

---

ivy.xml

This pull request is one of pull-requests related to PDI-13231.
If you apply this request  you have to apply other pull-requests from this set:
https://github.com/pentaho/data-access/pull/657
https://github.com/pentaho/pentaho-platform/pull/2411
https://github.com/pentaho/pdi-agile-bi-plugin/pull/38
@mbatchelor , @mdamour1976  please review.

[PDI-13231] - upgrade axis2 to 1.5

---

test/org/pentaho/metadata/SqlOpenFormulaTest.java
test/org/pentaho/pms/MQLQueryTest.java

@pamval @dkincade please review

[TEST] - Fixing unit tests due to hqsql driver update

---

test-src/org/pentaho/metadata/libformula/FunctionsTest.java
test-src/org/pentaho/metadata/util/BooleanComparatorTest.java

What was done:
1) added tests for functions and boolean comparator

[TEST] -- imroving coverag for the project

---

src/org/pentaho/metadata/model/concept/util/DataFormatter.java
test-src/org/pentaho/metadata/model/concept/util/DataFormatterTest.java

@pamval, could you merge it too. Its condition was missed during update the pr.

[PDB-1427] Default date formats in dashboard and PIR are not same - added missed condition

---

src/org/pentaho/metadata/query/impl/ietl/InlineEtlQueryExecutor.java

A refactor of SelectValuesMeta broke a
InlineEtlQueryExecutor, which was using
a getter as a setter (ie changing a property
backed by an array).

[TEST] Fixing failing IT tests.

---

build.properties

Reverts pentaho/pentaho-metadata#99

Revert "[PPP-3537] - Use of vulnerable component com.thoughtworks.xstream v1.…"

---

src/org/pentaho/metadata/query/impl/sql/SqlOpenFormula.java
test-src/org/pentaho/metadata/SqlOpenFormulaIT.java

- transform IN filter in 2 different filters (IN (..) OR ..Is Null)

[PIR-646]-Cannot filter by null values

---

src/org/pentaho/metadata/query/impl/sql/SqlOpenFormula.java
test-src/org/pentaho/metadata/SqlOpenFormulaIT.java

- transform in 2 different filters

[SP-2992][PIR-646]-Cannot filter by null values

---

src/org/pentaho/metadata/util/XmiParser.java

@pamval, @mbatchelor,  here is clone of https://github.com/pentaho/pentaho-metadata/pull/122 to 7.0. Thanks.

[PPP-3506] - XXE Security Vulnerability in xml parsers

---

ivy.xml

[PPP-3570] - revert

---

src/test/java/org/pentaho/metadata/MondrianModelExporterTest.java

What was done:
fixed tests after fixing errors in XL encoding

[CLEANUP] -- fix unit tests

---

pom.xml

What was done:
fixed integration test by controlling numbers of threads run

[TEST] - fixing integration tests

---

pom.xml

[CLEANUP] upgrade commons-io and exclude javassist

---

src/main/java/org/pentaho/metadata/automodel/PhysicalTableImporter.java

Needs https://github.com/pentaho/pdi-dataservice-plugin/pull/84 and https://github.com/pentaho/pentaho-kettle/pull/3416.
@pentaho/millenniumfalcon please review.

[BACKLOG-12456] Copy step's formatting mask metadata to physical table metadata automodeling

---

src/org/pentaho/metadata/query/model/util/QueryXmlHelper.java
test-src/org/pentaho/metadata/query/model/util/QueryXmlHelperTest.java

- getDomain with .xmi if get null first time
- added unittest

[SP-3298][BISERVER-13522]-Migrated or Imported Interactive reports do not run due to missing XMI extension

---

src/org/pentaho/metadata/query/model/util/QueryXmlHelper.java
test-src/org/pentaho/metadata/query/model/util/QueryXmlHelperTest.java

- getDomain with .xmi if get null first time
- added unittest

[SP-3297][BISERVER-13522]-Migrated or Imported Interactive reports do not run due to missing XMI extension

---

src/org/pentaho/metadata/query/model/util/QueryXmlHelper.java
test-src/org/pentaho/metadata/query/model/util/QueryXmlHelperTest.java

- getDomain with .xmi if get null first time
- added unittest

[SP-3297][BISERVER-13522]-Migrated or Imported Interactive reports donot run due to missing XMI extension

---

pom.xml

TO BE MERGED BY BUILDTEAM ONLY!   Pending upstream mavenization of reporting.

[BACKLOG-12334] GAV changes for reporting

---

src/main/java/org/pentaho/metadata/query/impl/sql/SqlGenerator.java
src/test/java/org/pentaho/metadata/query/impl/sql/SqlGeneratorTest.java

- check that tablename contains "," (means tableName must be surrounded by parenthesis)

[BISERVER-13476]-Interactive report throws an ORA-00972: identifier is too long error

---

src/main/java/org/pentaho/metadata/automodel/PhysicalTableImporter.java
src/test/java/org/pentaho/metadata/automodel/PhysicalTableImporterTest.java

@pentaho/millenniumfalcon, @pentaho/ackbar please review. See notes in http://jira.pentaho.com/browse/BACKLOG-15502?focusedCommentId=293902&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-293902.

[BACKLOG-15502] Rename SqlPhysicalColumn's mask prop to avoid conflit with LogicalColumn's mask

---

src/org/pentaho/metadata/query/impl/sql/SqlGenerator.java
test-src/org/pentaho/metadata/query/impl/sql/SqlGeneratorTest.java

- check that tablename contains "," (means tableName must be surrounded by parenthesis)

[SP-3440][BISERVER-13476]-Interactive report throws an ORA-00972: identifier is too long error

---

src/org/pentaho/metadata/query/impl/sql/SqlGenerator.java
test-src/org/pentaho/metadata/query/impl/sql/SqlGeneratorTest.java

- check that tablename contains "," (means tableName must be surrounded by parenthesis)

[SP-3439][BISERVER-13476]-Interactive report throws an ORA-00972: identifier is too long error

---

src/main/java/org/pentaho/pms/factory/CwmSchemaFactory.java
src/test/java/org/pentaho/pms/factory/CwmSchemaFactoryTest.java

- log level was changed
- test was added

[PMD-1064] Error when saving an Imported XMI file

---

src/main/java/org/pentaho/pms/mql/dialect/DefaultSQLDialect.java

- support for an array of Date was added

[PIR-1340] Error occurs when checkbox prompt used with date field.

---

src/org/pentaho/pms/mql/dialect/DefaultSQLDialect.java

[SP-3630] Backport of PIR-1340 - Error occurs when checkbox prompt used with date field. (6.1 Suite)

---

src/main/java/org/pentaho/pms/mql/dialect/DefaultSQLDialect.java

[SP-3629] Backport of PIR-1340 - Error occurs when checkbox prompt used with date field. (7.1 Suite)

---

src/main/java/org/pentaho/metadata/util/MondrianModelExporter.java

Reverts pentaho/pentaho-metadata#161

Revert "[SP-3717][BISERVER-10319]-Unable to move a DSW data source to another 5.X server."

---

src/it/java/org/pentaho/metadata/XmiParserIT.java
src/main/java/org/pentaho/metadata/util/XmiParser.java
src/main/resources/org/pentaho/metadata/messages/messages.properties

Reverts pentaho/pentaho-metadata#166 due to regression found. See BACKLOG-19112.

Revert "[BISERVER-13338] - Data source domain object mutation while re-parsing"

---

src/main/java/org/pentaho/metadata/automodel/PhysicalTableImporter.java
src/main/java/org/pentaho/metadata/model/concept/types/DataType.java
src/main/java/org/pentaho/pms/schema/concept/types/datatype/ConceptPropertyDataType.java
src/main/java/org/pentaho/pms/schema/concept/types/datatype/DataTypeSettings.java
src/main/resources/org/pentaho/pms/locale/messages.properties
src/test/java/org/pentaho/metadata/automodel/PhysicalTableImporterTest.java

Reverts pentaho/pentaho-metadata#172

Revert "[ANALYZER-3559]-When filtering the date field (format YYYY-MM-DD HH:MM:SS.0) it shows "The report has no data""

---

src/main/resources/org/pentaho/pms/locale/messages.properties

@ricardosilva88 @pentaho-lmartins

[PMD-1077] CLONE - Able to Publish a model with no domain name

---

src/main/resources/org/pentaho/pms/locale/messages.properties

[SP-4643] Backport of PMD-1077 - CLONE - Able to Publish a model with no domain name (8.1 Suite)

---

src/it/java/org/pentaho/metadata/XmiParserIT.java
src/main/java/org/pentaho/metadata/util/SerializationService.java

@smmribeiro 
@bcostahitachivantara 
@renato-s

[PPP-4704] - Vulnerable Component: xstream-1.4.17

---

src/it/java/org/pentaho/metadata/XmiParserIT.java
src/main/java/org/pentaho/metadata/util/SerializationService.java

@smmribeiro 
@renato-s 
@bcostahitachivantara

[SP-6250] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.3 Suite)

---

src/it/java/org/pentaho/metadata/XmiParserIT.java
src/main/java/org/pentaho/metadata/util/SerializationService.java

@smmribeiro 
@bcostahitachivantara 
@renato-s

[SP-6251] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.4 Suite)

---

pom.xml

@smmribeiro 
@renato-s 
@bcostahitachivantara

[PPP-4802] -  Vulnerable Component: hsqldb

---

pom.xml

Reverts pentaho/pentaho-metadata#230

Revert "[PPP-4802] -  Vulnerable Component: hsqldb"

---

src/it/java/org/pentaho/metadata/AdvancedQueryIT.java
src/it/java/org/pentaho/metadata/SQLModelGeneratorIT.java
src/it/java/org/pentaho/metadata/SqlGeneratorIT.java
src/it/java/org/pentaho/metadata/SqlOpenFormulaIT.java
src/it/java/org/pentaho/metadata/ThinModelIT.java
src/it/java/org/pentaho/metadata/ThinQueryIT.java
src/it/java/org/pentaho/metadata/XmiParserIT.java
src/it/java/org/pentaho/pms/MQLQueryIT.java
src/it/java/org/pentaho/pms/MQLQueryImplIT.java
src/it/java/org/pentaho/pms/mql/dialect/SQLJoinIT.java
src/test/java/org/pentaho/metadata/libformula/FunctionsTest.java

Several fixes, clean ups and refactorings...

[BACKLOG-38674] Integration Tests are outdated and some do not compile.

---

pom.xml

Reverts pentaho/pentaho-metadata#233

Revert "[PDI-19906] - Google BigQuery Simba driver version 1.3.3.1004 in Pentaho"

---

src/main/java/org/pentaho/metadata/query/model/util/QueryXmlHelper.java
src/main/java/org/pentaho/metadata/util/XmiParser.java
src/main/java/org/pentaho/pms/mql/MQLQueryImpl.java
src/test/java/org/pentaho/metadata/util/XmiParserTest.java

[BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code
[BACKLOG-36134]: https://hv-eng.atlassian.net/browse/BACKLOG-36134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code

---

src/main/java/org/pentaho/metadata/query/model/util/QueryXmlHelper.java
src/main/java/org/pentaho/metadata/util/XmiParser.java
src/main/java/org/pentaho/pms/mql/MQLQueryImpl.java
src/test/java/org/pentaho/metadata/util/XmiParserTest.java

[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

---

src/main/java/org/pentaho/metadata/query/model/util/QueryXmlHelper.java

[PIR-1524] - Load PIR in blank without error message, InteractiveAdhocReportUtils.ERROR_0002 - Unable to load report query

---

pom.xml

[BACKLOG-43938]-Fixing test1 pipeline test failures running on JDK21
[BACKLOG-43938]: https://hv-eng.atlassian.net/browse/BACKLOG-43938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43938]-Fixing test1 pipeline test failures running on JDK21

---

src/main/java/org/pentaho/metadata/query/model/util/QueryXmlHelper.java
src/main/java/org/pentaho/metadata/util/XmiParser.java
src/main/java/org/pentaho/pms/mql/MQLQueryImpl.java

Reverts pentaho/pentaho-metadata#252
@pentaho/tatooine_dev

Revert "fix: add proper initialization to XML parser [PPP-5719]"
